### PR TITLE
update to bevy 0.16

### PR DESCRIPTION
**Pull request by slyedoc**
Pretty easy update, did use my own branch for bevy_egui.  (Didn't see Friz64 branch before I started)

Ran though all the examples and all working.

### CODE REVIEW

**Comment by tigerplush** [comment]
you beat me by 5 hours 🤣 

it does not work with bevy v0.16-rc2 in my project

```
error[E0603]: type alias `HashMap` is private
  -->[...]\checkouts\bevy_egui-fc270bb4cc3fc631\ae37af7\src\output.rs:26:61
   |
26 |     #[cfg(windows)] mut last_cursor_icon: Local<bevy_utils::HashMap<Entity, egui::CursorIcon>>,
   |                                                             ^^^^^^^ private type alias
   |
note: the type alias `HashMap` is defined here
  --> [...]\bevy_utils-0.16.0-rc.2\src\lib.rs:46:9
   |
46 |         collections::HashMap,
   |         ^^^^^^^^^^^^^^^^^^^^
help: consider importing this type alias instead
   |
26 -     #[cfg(windows)] mut last_cursor_icon: Local<bevy_utils::HashMap<Entity, egui::CursorIcon>>,
26 +     #[cfg(windows)] mut last_cursor_icon: Local<bevy_platform_support::collections::HashMap<Entity, egui::CursorIcon>>,
   |
help: import `HashMap` directly
   |
26 -     #[cfg(windows)] mut last_cursor_icon: Local<bevy_utils::HashMap<Entity, egui::CursorIcon>>,
26 +     #[cfg(windows)] mut last_cursor_icon: Local<bevy_platform_support::collections::hash_map::HashMap>,
   |

```

**Comment by slyedoc** [comment]
Ah, mb, mind testing it now.

**Comment by tigerplush** [comment]
I've cloned your repository, it has some errors with `cargo run --example world_inspector`:

```
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `bevy`
  --> [...]\bevy_egui-fc270bb4cc3fc631\9a034ed\src\output.rs:26:49
   |
26 |     #[cfg(windows)] mut last_cursor_icon: Local<bevy::platform_support::collections::HashMap<Entity, egui::CursorIcon>>,
   |                                                 ^^^^ use of unresolved module or unlinked crate `bevy`
   |
   = help: if you wanted to use a crate named `bevy`, use `cargo add bevy` to add it to your `Cargo.toml`
help: consider importing one of these modules
   |
1  + use std::collections;
   |
1  + use bevy_platform_support::collections;
   |
help: if you import `collections`, refer to it directly
   |
26 -     #[cfg(windows)] mut last_cursor_icon: Local<bevy::platform_support::collections::HashMap<Entity, egui::CursorIcon>>,
26 +     #[cfg(windows)] mut last_cursor_icon: Local<collections::HashMap<Entity, egui::CursorIcon>>,
   |
```

the same happens in my project 🤔

**Comment by slyedoc** [comment]
I udpated it, https://github.com/slyedoc/bevy_egui/blob/bevy_0.16/src/output.rs#L26, might need to run `cargo update`

**Comment by tigerplush** [comment]
still the same problem, even after running `cargo update`. Am I doing something wrong?

**Comment by tigerplush** [comment]
All examples compile and work now on windows, but:

state_inspector has the error:
``` 
thread 'main' panicked at [...]\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\bevy_state-0.16.0-rc.2\src\app.rs:104:67:
The `StateTransition` schedule is missing. Did you forget to add StatesPlugin or DefaultPlugins before calling init_state?
```

I assume that is an old error?

**Comment by mnmaita** [comment]
> All examples compile and work now on windows, but:
> 
> state_inspector has the error:
> 
> ```
> thread 'main' panicked at [...]\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\bevy_state-0.16.0-rc.2\src\app.rs:104:67:
> The `StateTransition` schedule is missing. Did you forget to add StatesPlugin or DefaultPlugins before calling init_state?
> ```
> 
> I assume that is an old error?

Could this be because `bevy_state` feature is missing in bevy's dev-dependencies entry? cc @slyedoc

**Comment by slyedoc** [comment]
Good catch, added bevy_state to dev-dependencies

**Comment by vladbat00** [comment]
Hi! Just a heads up that there's an RC version of `bevy_egui` now, and there's a little breaking change added, which basically requires to remove existing `add_plugins(EguiPlugin { ... })` calls (see https://github.com/vladbat00/bevy_egui/blob/b6a043b1661e2e3a0a948314c18c94958b91b716/src/lib.rs#L299-L319)

**Comment by slyedoc** [comment]
Yea, just saw that myself, my bevy_egui is outdated, mb.

**Comment by slyedoc** [comment]
The scope of this PR is far more than I planned for with the changes to bevy_egui, feel free to close this.

**Comment by jakobhellermann** [comment]
Thanks for the PR! I'm gonna merge this and do any remaining updates in the main branch

**Comment by jakobhellermann** [comment]
for anyone looking for the status, see #248. right now I'm just waiting on `bevy_egui` to release

**Comment by vladbat00** [comment]
@jakobhellermann done ☺️
