### ISSUE TITLE
WorldInspectorPlugin example in readme does not compile in bevy 0.10

### ISSUE THREAD

**Issue by kALLEBALIK** [jakobhellermann/bevy-inspector-egui#127]
### Current example code:
```rust
use bevy::prelude::*;
use bevy_inspector_egui::quick::WorldInspectorPlugin;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(WorldInspectorPlugin)
        .run();
}
```
### error: 
```
error[E0423]: expected value, found struct `WorldInspectorPlugin`
  --> src\main.rs:7:21
   |
7  |         .add_plugin(WorldInspectorPlugin)
   |                     ^^^^^^^^^^^^^^^^^^^^ help: use struct literal syntax instead: `WorldInspectorPlugin { condition: val }`
```

### Solution:
Use WorldInspectorPlugin default constructor.
```rust
use bevy::prelude::*;
use bevy_inspector_egui::quick::WorldInspectorPlugin;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(WorldInspectorPlugin::default())
        .run();
}
```
